# Generated by Django 3.1b1 on 2020-09-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brief_History', models.CharField(max_length=3000)),
                ('Objectives', models.CharField(max_length=3000)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Introduction',
            },
        ),
        migrations.CreateModel(
            name='Water_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sources', models.CharField(max_length=4000)),
                ('Quality', models.CharField(max_length=4000)),
                ('Physical_Analysis', models.CharField(max_length=4500)),
                ('Turbidity', models.CharField(max_length=4500)),
            ],
            options={
                'verbose_name_plural': 'Water_Analysis',
            },
        ),
        migrations.CreateModel(
            name='Water_Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coagulation', models.CharField(max_length=4000)),
                ('Sedimentation', models.CharField(max_length=4000)),
                ('Chlorination', models.CharField(max_length=4000)),
                ('Water_Analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.water_analysis')),
            ],
            options={
                'verbose_name_plural': 'Water_Treatment',
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mission_Statement', models.CharField(max_length=3000)),
                ('Quality_control_unit', models.CharField(max_length=3500)),
                ('Laboratory_instrument', models.CharField(max_length=3500)),
                ('Introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.introduction')),
            ],
            options={
                'verbose_name_plural': 'Water',
            },
        ),
    ]
