# Generated by Django 3.1b1 on 2020-09-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='Introduction',
            new_name='introduction',
        ),
    ]
